/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define maxPrivateIEs (65535)
#define maxProtocolExtensions (65535)
#define maxProtocolIEs (65535)
#define maxnoofAllowedAreas (16)
#define maxnoofAllowedS_NSSAIs (8)
#define maxnoofBPLMNs (12)
#define maxnoofCellIDforWarning (65535)
#define maxnoofCellinAoI (256)
#define maxnoofCellinEAI (65535)
#define maxnoofCellinTAI (65535)
#define maxnoofCellsingNB (16384)
#define maxnoofCellsinngeNB (256)
#define maxnoofCellsinUEHistoryInfo (16)
#define maxnoofCellsUEMovingTrajectory (16)
#define maxnoofDRBs (32)
#define maxnoofEmergencyAreaID (65535)
#define maxnoofEAIforRestart (256)
#define maxnoofEPLMNs (15)
#define maxnoofEPLMNsPlusOne (16)
#define maxnoofE_RABs (256)
#define maxnoofErrors (256)
#define maxnoofForbTACs (4096)
#define maxnoofMultiConnectivity (4)
#define maxnoofMultiConnectivityMinusOne (3)
#define maxnoofNGConnectionsToReset (65536)
#define maxnoofPDUSessions (256)
#define maxnoofPLMNs (12)
#define maxnoofQosFlows (64)
#define maxnoofRANNodeinAoI (64)
#define maxnoofRecommendedCells (16)
#define maxnoofRecommendedRANNodes (16)
#define maxnoofAoI (64)
#define maxnoofServedGUAMIs (256)
#define maxnoofSliceItems (1024)
#define maxnoofTACs (256)
#define maxnoofTAIforInactive (16)
#define maxnoofTAIforPaging (16)
#define maxnoofTAIforRestart (2048)
#define maxnoofTAIforWarning (65535)
#define maxnoofTAIinAoI (16)
#define maxnoofTimePeriods (2)
#define maxnoofTNLAssociations (32)
#define maxnoofXnExtTLAs (2)
#define maxnoofXnGTP_TLAs (16)
#define maxnoofXnTLAs (16)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
