/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_BroadcastCancelledAreaList_H_
#define	_BroadcastCancelledAreaList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BroadcastCancelledAreaList_PR {
	BroadcastCancelledAreaList_PR_NOTHING,	/* No components present */
	BroadcastCancelledAreaList_PR_cellIDCancelledEUTRA,
	BroadcastCancelledAreaList_PR_tAICancelledEUTRA,
	BroadcastCancelledAreaList_PR_emergencyAreaIDCancelledEUTRA,
	BroadcastCancelledAreaList_PR_cellIDCancelledNR,
	BroadcastCancelledAreaList_PR_tAICancelledNR,
	BroadcastCancelledAreaList_PR_emergencyAreaIDCancelledNR,
	BroadcastCancelledAreaList_PR_choice_Extensions
} BroadcastCancelledAreaList_PR;

/* Forward declarations */
struct CellIDCancelledEUTRA;
struct TAICancelledEUTRA;
struct EmergencyAreaIDCancelledEUTRA;
struct CellIDCancelledNR;
struct TAICancelledNR;
struct EmergencyAreaIDCancelledNR;
struct ProtocolIE_SingleContainer;

/* BroadcastCancelledAreaList */
typedef struct BroadcastCancelledAreaList {
	BroadcastCancelledAreaList_PR present;
	union BroadcastCancelledAreaList_u {
		struct CellIDCancelledEUTRA	*cellIDCancelledEUTRA;
		struct TAICancelledEUTRA	*tAICancelledEUTRA;
		struct EmergencyAreaIDCancelledEUTRA	*emergencyAreaIDCancelledEUTRA;
		struct CellIDCancelledNR	*cellIDCancelledNR;
		struct TAICancelledNR	*tAICancelledNR;
		struct EmergencyAreaIDCancelledNR	*emergencyAreaIDCancelledNR;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BroadcastCancelledAreaList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BroadcastCancelledAreaList;
extern asn_CHOICE_specifics_t asn_SPC_BroadcastCancelledAreaList_specs_1;
extern asn_TYPE_member_t asn_MBR_BroadcastCancelledAreaList_1[7];
extern asn_per_constraints_t asn_PER_type_BroadcastCancelledAreaList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _BroadcastCancelledAreaList_H_ */
#include <asn_internal.h>
