/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_BroadcastCompletedAreaList_H_
#define	_BroadcastCompletedAreaList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BroadcastCompletedAreaList_PR {
	BroadcastCompletedAreaList_PR_NOTHING,	/* No components present */
	BroadcastCompletedAreaList_PR_cellIDBroadcastEUTRA,
	BroadcastCompletedAreaList_PR_tAIBroadcastEUTRA,
	BroadcastCompletedAreaList_PR_emergencyAreaIDBroadcastEUTRA,
	BroadcastCompletedAreaList_PR_cellIDBroadcastNR,
	BroadcastCompletedAreaList_PR_tAIBroadcastNR,
	BroadcastCompletedAreaList_PR_emergencyAreaIDBroadcastNR,
	BroadcastCompletedAreaList_PR_choice_Extensions
} BroadcastCompletedAreaList_PR;

/* Forward declarations */
struct CellIDBroadcastEUTRA;
struct TAIBroadcastEUTRA;
struct EmergencyAreaIDBroadcastEUTRA;
struct CellIDBroadcastNR;
struct TAIBroadcastNR;
struct EmergencyAreaIDBroadcastNR;
struct ProtocolIE_SingleContainer;

/* BroadcastCompletedAreaList */
typedef struct BroadcastCompletedAreaList {
	BroadcastCompletedAreaList_PR present;
	union BroadcastCompletedAreaList_u {
		struct CellIDBroadcastEUTRA	*cellIDBroadcastEUTRA;
		struct TAIBroadcastEUTRA	*tAIBroadcastEUTRA;
		struct EmergencyAreaIDBroadcastEUTRA	*emergencyAreaIDBroadcastEUTRA;
		struct CellIDBroadcastNR	*cellIDBroadcastNR;
		struct TAIBroadcastNR	*tAIBroadcastNR;
		struct EmergencyAreaIDBroadcastNR	*emergencyAreaIDBroadcastNR;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BroadcastCompletedAreaList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BroadcastCompletedAreaList;

#ifdef __cplusplus
}
#endif

#endif	/* _BroadcastCompletedAreaList_H_ */
#include <asn_internal.h>
