/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_CellIDCancelledNR_H_
#define	_CellIDCancelledNR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CellIDCancelledNR_Item;

/* CellIDCancelledNR */
typedef struct CellIDCancelledNR {
	A_SEQUENCE_OF(struct CellIDCancelledNR_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellIDCancelledNR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellIDCancelledNR;
extern asn_SET_OF_specifics_t asn_SPC_CellIDCancelledNR_specs_1;
extern asn_TYPE_member_t asn_MBR_CellIDCancelledNR_1[1];
extern asn_per_constraints_t asn_PER_type_CellIDCancelledNR_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CellIDCancelledNR_H_ */
#include <asn_internal.h>
