/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_CNTypeRestrictionsForEquivalentItem_H_
#define	_CNTypeRestrictionsForEquivalentItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMNIdentity.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CNTypeRestrictionsForEquivalentItem__cn_Type {
	CNTypeRestrictionsForEquivalentItem__cn_Type_epc_forbidden	= 0,
	CNTypeRestrictionsForEquivalentItem__cn_Type_fiveGC_forbidden	= 1
	/*
	 * Enumeration is extensible
	 */
} e_CNTypeRestrictionsForEquivalentItem__cn_Type;

/* Forward declarations */
struct ProtocolExtensionContainer;

/* CNTypeRestrictionsForEquivalentItem */
typedef struct CNTypeRestrictionsForEquivalentItem {
	PLMNIdentity_t	 plmnIdentity;
	long	 cn_Type;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CNTypeRestrictionsForEquivalentItem_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_cn_Type_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CNTypeRestrictionsForEquivalentItem;
extern asn_SEQUENCE_specifics_t asn_SPC_CNTypeRestrictionsForEquivalentItem_specs_1;
extern asn_TYPE_member_t asn_MBR_CNTypeRestrictionsForEquivalentItem_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _CNTypeRestrictionsForEquivalentItem_H_ */
#include <asn_internal.h>
