/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_CPTransportLayerInformation_H_
#define	_CPTransportLayerInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransportLayerAddress.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CPTransportLayerInformation_PR {
	CPTransportLayerInformation_PR_NOTHING,	/* No components present */
	CPTransportLayerInformation_PR_endpointIPAddress,
	CPTransportLayerInformation_PR_choice_Extensions
} CPTransportLayerInformation_PR;

/* Forward declarations */
struct ProtocolIE_SingleContainer;

/* CPTransportLayerInformation */
typedef struct CPTransportLayerInformation {
	CPTransportLayerInformation_PR present;
	union CPTransportLayerInformation_u {
		TransportLayerAddress_t	 endpointIPAddress;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CPTransportLayerInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CPTransportLayerInformation;
extern asn_CHOICE_specifics_t asn_SPC_CPTransportLayerInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_CPTransportLayerInformation_1[2];
extern asn_per_constraints_t asn_PER_type_CPTransportLayerInformation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CPTransportLayerInformation_H_ */
#include <asn_internal.h>
