/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_DRBsSubjectToStatusTransferItem_H_
#define	_DRBsSubjectToStatusTransferItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DRB-ID.h"
#include "DRBStatusUL.h"
#include "DRBStatusDL.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* DRBsSubjectToStatusTransferItem */
typedef struct DRBsSubjectToStatusTransferItem {
	DRB_ID_t	 dRB_ID;
	DRBStatusUL_t	 dRBStatusUL;
	DRBStatusDL_t	 dRBStatusDL;
	struct ProtocolExtensionContainer	*iE_Extension;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRBsSubjectToStatusTransferItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRBsSubjectToStatusTransferItem;
extern asn_SEQUENCE_specifics_t asn_SPC_DRBsSubjectToStatusTransferItem_specs_1;
extern asn_TYPE_member_t asn_MBR_DRBsSubjectToStatusTransferItem_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _DRBsSubjectToStatusTransferItem_H_ */
#include <asn_internal.h>
