/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_EmergencyAreaIDBroadcastNR_Item_H_
#define	_EmergencyAreaIDBroadcastNR_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EmergencyAreaID.h"
#include "CompletedCellsInEAI-NR.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* EmergencyAreaIDBroadcastNR-Item */
typedef struct EmergencyAreaIDBroadcastNR_Item {
	EmergencyAreaID_t	 emergencyAreaID;
	CompletedCellsInEAI_NR_t	 completedCellsInEAI_NR;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EmergencyAreaIDBroadcastNR_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EmergencyAreaIDBroadcastNR_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_EmergencyAreaIDBroadcastNR_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_EmergencyAreaIDBroadcastNR_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _EmergencyAreaIDBroadcastNR_Item_H_ */
#include <asn_internal.h>
