/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_ExpectedUEBehaviour_H_
#define	_ExpectedUEBehaviour_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ExpectedHOInterval.h"
#include "ExpectedUEMobility.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ExpectedUEActivityBehaviour;
struct ExpectedUEMovingTrajectory;
struct ProtocolExtensionContainer;

/* ExpectedUEBehaviour */
typedef struct ExpectedUEBehaviour {
	struct ExpectedUEActivityBehaviour	*expectedUEActivityBehaviour;	/* OPTIONAL */
	ExpectedHOInterval_t	*expectedHOInterval;	/* OPTIONAL */
	ExpectedUEMobility_t	*expectedUEMobility;	/* OPTIONAL */
	struct ExpectedUEMovingTrajectory	*expectedUEMovingTrajectory;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExpectedUEBehaviour_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExpectedUEBehaviour;
extern asn_SEQUENCE_specifics_t asn_SPC_ExpectedUEBehaviour_specs_1;
extern asn_TYPE_member_t asn_MBR_ExpectedUEBehaviour_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _ExpectedUEBehaviour_H_ */
#include <asn_internal.h>
