/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_FiveG_S_TMSI_H_
#define	_FiveG_S_TMSI_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AMFSetID.h"
#include "AMFPointer.h"
#include "FiveG-TMSI.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* FiveG-S-TMSI */
typedef struct FiveG_S_TMSI {
	AMFSetID_t	 aMFSetID;
	AMFPointer_t	 aMFPointer;
	FiveG_TMSI_t	 fiveG_TMSI;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FiveG_S_TMSI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_FiveG_S_TMSI;
extern asn_SEQUENCE_specifics_t asn_SPC_FiveG_S_TMSI_specs_1;
extern asn_TYPE_member_t asn_MBR_FiveG_S_TMSI_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _FiveG_S_TMSI_H_ */
#include <asn_internal.h>
