/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_GlobalRANNodeID_H_
#define	_GlobalRANNodeID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GlobalRANNodeID_PR {
	GlobalRANNodeID_PR_NOTHING,	/* No components present */
	GlobalRANNodeID_PR_globalGNB_ID,
	GlobalRANNodeID_PR_globalNgENB_ID,
	GlobalRANNodeID_PR_globalN3IWF_ID,
	GlobalRANNodeID_PR_choice_Extensions
} GlobalRANNodeID_PR;

/* Forward declarations */
struct GlobalGNB_ID;
struct GlobalNgENB_ID;
struct GlobalN3IWF_ID;
struct ProtocolIE_SingleContainer;

/* GlobalRANNodeID */
typedef struct GlobalRANNodeID {
	GlobalRANNodeID_PR present;
	union GlobalRANNodeID_u {
		struct GlobalGNB_ID	*globalGNB_ID;
		struct GlobalNgENB_ID	*globalNgENB_ID;
		struct GlobalN3IWF_ID	*globalN3IWF_ID;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GlobalRANNodeID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GlobalRANNodeID;
extern asn_CHOICE_specifics_t asn_SPC_GlobalRANNodeID_specs_1;
extern asn_TYPE_member_t asn_MBR_GlobalRANNodeID_1[4];
extern asn_per_constraints_t asn_PER_type_GlobalRANNodeID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _GlobalRANNodeID_H_ */
#include <asn_internal.h>
