/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "LocationReportingRequestType.h"

#include "AreaOfInterestList.h"
#include "ProtocolExtensionContainer.h"
static asn_TYPE_member_t asn_MBR_LocationReportingRequestType_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LocationReportingRequestType, eventType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LocationReportingRequestType, reportArea),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReportArea,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"reportArea"
		},
	{ ATF_POINTER, 3, offsetof(struct LocationReportingRequestType, areaOfInterestList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AreaOfInterestList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"areaOfInterestList"
		},
	{ ATF_POINTER, 2, offsetof(struct LocationReportingRequestType, locationReportingReferenceIDToBeCancelled),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LocationReportingReferenceID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"locationReportingReferenceIDToBeCancelled"
		},
	{ ATF_POINTER, 1, offsetof(struct LocationReportingRequestType, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_178P71,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_LocationReportingRequestType_oms_1[] = { 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_LocationReportingRequestType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LocationReportingRequestType_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* reportArea */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* areaOfInterestList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* locationReportingReferenceIDToBeCancelled */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_LocationReportingRequestType_specs_1 = {
	sizeof(struct LocationReportingRequestType),
	offsetof(struct LocationReportingRequestType, _asn_ctx),
	asn_MAP_LocationReportingRequestType_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_LocationReportingRequestType_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LocationReportingRequestType = {
	"LocationReportingRequestType",
	"LocationReportingRequestType",
	&asn_OP_SEQUENCE,
	asn_DEF_LocationReportingRequestType_tags_1,
	sizeof(asn_DEF_LocationReportingRequestType_tags_1)
		/sizeof(asn_DEF_LocationReportingRequestType_tags_1[0]), /* 1 */
	asn_DEF_LocationReportingRequestType_tags_1,	/* Same as above */
	sizeof(asn_DEF_LocationReportingRequestType_tags_1)
		/sizeof(asn_DEF_LocationReportingRequestType_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LocationReportingRequestType_1,
	5,	/* Elements count */
	&asn_SPC_LocationReportingRequestType_specs_1	/* Additional specs */
};

