/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_NGRAN_CGI_H_
#define	_NGRAN_CGI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGRAN_CGI_PR {
	NGRAN_CGI_PR_NOTHING,	/* No components present */
	NGRAN_CGI_PR_nR_CGI,
	NGRAN_CGI_PR_eUTRA_CGI,
	NGRAN_CGI_PR_choice_Extensions
} NGRAN_CGI_PR;

/* Forward declarations */
struct NR_CGI;
struct EUTRA_CGI;
struct ProtocolIE_SingleContainer;

/* NGRAN-CGI */
typedef struct NGRAN_CGI {
	NGRAN_CGI_PR present;
	union NGRAN_CGI_u {
		struct NR_CGI	*nR_CGI;
		struct EUTRA_CGI	*eUTRA_CGI;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGRAN_CGI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGRAN_CGI;
extern asn_CHOICE_specifics_t asn_SPC_NGRAN_CGI_specs_1;
extern asn_TYPE_member_t asn_MBR_NGRAN_CGI_1[3];
extern asn_per_constraints_t asn_PER_type_NGRAN_CGI_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NGRAN_CGI_H_ */
#include <asn_internal.h>
