/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_NumberOfBroadcastsRequested_H_
#define	_NumberOfBroadcastsRequested_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* NumberOfBroadcastsRequested */
typedef long	 NumberOfBroadcastsRequested_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NumberOfBroadcastsRequested;
asn_struct_free_f NumberOfBroadcastsRequested_free;
asn_struct_print_f NumberOfBroadcastsRequested_print;
asn_constr_check_f NumberOfBroadcastsRequested_constraint;
ber_type_decoder_f NumberOfBroadcastsRequested_decode_ber;
der_type_encoder_f NumberOfBroadcastsRequested_encode_der;
xer_type_decoder_f NumberOfBroadcastsRequested_decode_xer;
xer_type_encoder_f NumberOfBroadcastsRequested_encode_xer;
oer_type_decoder_f NumberOfBroadcastsRequested_decode_oer;
oer_type_encoder_f NumberOfBroadcastsRequested_encode_oer;
per_type_decoder_f NumberOfBroadcastsRequested_decode_uper;
per_type_encoder_f NumberOfBroadcastsRequested_encode_uper;
per_type_decoder_f NumberOfBroadcastsRequested_decode_aper;
per_type_encoder_f NumberOfBroadcastsRequested_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NumberOfBroadcastsRequested_H_ */
#include <asn_internal.h>
