/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_OverloadStartNSSAIList_H_
#define	_OverloadStartNSSAIList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OverloadStartNSSAIItem;

/* OverloadStartNSSAIList */
typedef struct OverloadStartNSSAIList {
	A_SEQUENCE_OF(struct OverloadStartNSSAIItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OverloadStartNSSAIList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OverloadStartNSSAIList;
extern asn_SET_OF_specifics_t asn_SPC_OverloadStartNSSAIList_specs_1;
extern asn_TYPE_member_t asn_MBR_OverloadStartNSSAIList_1[1];
extern asn_per_constraints_t asn_PER_type_OverloadStartNSSAIList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _OverloadStartNSSAIList_H_ */
#include <asn_internal.h>
