/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_OverloadResponse_H_
#define	_OverloadResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "OverloadAction.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum OverloadResponse_PR {
	OverloadResponse_PR_NOTHING,	/* No components present */
	OverloadResponse_PR_overloadAction,
	OverloadResponse_PR_choice_Extensions
} OverloadResponse_PR;

/* Forward declarations */
struct ProtocolIE_SingleContainer;

/* OverloadResponse */
typedef struct OverloadResponse {
	OverloadResponse_PR present;
	union OverloadResponse_u {
		OverloadAction_t	 overloadAction;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OverloadResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OverloadResponse;
extern asn_CHOICE_specifics_t asn_SPC_OverloadResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_OverloadResponse_1[2];
extern asn_per_constraints_t asn_PER_type_OverloadResponse_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _OverloadResponse_H_ */
#include <asn_internal.h>
