/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_PDUSessionAggregateMaximumBitRate_H_
#define	_PDUSessionAggregateMaximumBitRate_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BitRate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* PDUSessionAggregateMaximumBitRate */
typedef struct PDUSessionAggregateMaximumBitRate {
	BitRate_t	 pDUSessionAggregateMaximumBitRateDL;
	BitRate_t	 pDUSessionAggregateMaximumBitRateUL;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDUSessionAggregateMaximumBitRate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDUSessionAggregateMaximumBitRate;

#ifdef __cplusplus
}
#endif

#endif	/* _PDUSessionAggregateMaximumBitRate_H_ */
#include <asn_internal.h>
