/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_PDUSessionResourceModifyItemModReq_H_
#define	_PDUSessionResourceModifyItemModReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PDUSessionID.h"
#include "NAS-PDU.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* PDUSessionResourceModifyItemModReq */
typedef struct PDUSessionResourceModifyItemModReq {
	PDUSessionID_t	 pDUSessionID;
	NAS_PDU_t	*nAS_PDU;	/* OPTIONAL */
	OCTET_STRING_t	 pDUSessionResourceModifyRequestTransfer;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDUSessionResourceModifyItemModReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDUSessionResourceModifyItemModReq;
extern asn_SEQUENCE_specifics_t asn_SPC_PDUSessionResourceModifyItemModReq_specs_1;
extern asn_TYPE_member_t asn_MBR_PDUSessionResourceModifyItemModReq_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _PDUSessionResourceModifyItemModReq_H_ */
#include <asn_internal.h>
