/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_PriorityLevelARP_H_
#define	_PriorityLevelARP_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PriorityLevelARP */
typedef long	 PriorityLevelARP_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PriorityLevelARP_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PriorityLevelARP;
asn_struct_free_f PriorityLevelARP_free;
asn_struct_print_f PriorityLevelARP_print;
asn_constr_check_f PriorityLevelARP_constraint;
ber_type_decoder_f PriorityLevelARP_decode_ber;
der_type_encoder_f PriorityLevelARP_encode_der;
xer_type_decoder_f PriorityLevelARP_decode_xer;
xer_type_encoder_f PriorityLevelARP_encode_xer;
oer_type_decoder_f PriorityLevelARP_decode_oer;
oer_type_encoder_f PriorityLevelARP_encode_oer;
per_type_decoder_f PriorityLevelARP_decode_uper;
per_type_encoder_f PriorityLevelARP_encode_uper;
per_type_decoder_f PriorityLevelARP_decode_aper;
per_type_encoder_f PriorityLevelARP_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PriorityLevelARP_H_ */
#include <asn_internal.h>
