/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_QosFlowAcceptedList_H_
#define	_QosFlowAcceptedList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct QosFlowAcceptedItem;

/* QosFlowAcceptedList */
typedef struct QosFlowAcceptedList {
	A_SEQUENCE_OF(struct QosFlowAcceptedItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} QosFlowAcceptedList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QosFlowAcceptedList;
extern asn_SET_OF_specifics_t asn_SPC_QosFlowAcceptedList_specs_1;
extern asn_TYPE_member_t asn_MBR_QosFlowAcceptedList_1[1];
extern asn_per_constraints_t asn_PER_type_QosFlowAcceptedList_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _QosFlowAcceptedList_H_ */
#include <asn_internal.h>
