/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_QosFlowAddOrModifyRequestItem_H_
#define	_QosFlowAddOrModifyRequestItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "QosFlowIdentifier.h"
#include "E-RAB-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct QosFlowLevelQosParameters;
struct ProtocolExtensionContainer;

/* QosFlowAddOrModifyRequestItem */
typedef struct QosFlowAddOrModifyRequestItem {
	QosFlowIdentifier_t	 qosFlowIdentifier;
	struct QosFlowLevelQosParameters	*qosFlowLevelQosParameters;	/* OPTIONAL */
	E_RAB_ID_t	*e_RAB_ID;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} QosFlowAddOrModifyRequestItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QosFlowAddOrModifyRequestItem;
extern asn_SEQUENCE_specifics_t asn_SPC_QosFlowAddOrModifyRequestItem_specs_1;
extern asn_TYPE_member_t asn_MBR_QosFlowAddOrModifyRequestItem_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _QosFlowAddOrModifyRequestItem_H_ */
#include <asn_internal.h>
