/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_QosFlowNotifyItem_H_
#define	_QosFlowNotifyItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "QosFlowIdentifier.h"
#include "NotificationCause.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* QosFlowNotifyItem */
typedef struct QosFlowNotifyItem {
	QosFlowIdentifier_t	 qosFlowIdentifier;
	NotificationCause_t	 notificationCause;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} QosFlowNotifyItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_QosFlowNotifyItem;
extern asn_SEQUENCE_specifics_t asn_SPC_QosFlowNotifyItem_specs_1;
extern asn_TYPE_member_t asn_MBR_QosFlowNotifyItem_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _QosFlowNotifyItem_H_ */
#include <asn_internal.h>
