/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_RANStatusTransfer_TransparentContainer_H_
#define	_RANStatusTransfer_TransparentContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DRBsSubjectToStatusTransferList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* RANStatusTransfer-TransparentContainer */
typedef struct RANStatusTransfer_TransparentContainer {
	DRBsSubjectToStatusTransferList_t	 dRBsSubjectToStatusTransferList;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANStatusTransfer_TransparentContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANStatusTransfer_TransparentContainer;

#ifdef __cplusplus
}
#endif

#endif	/* _RANStatusTransfer_TransparentContainer_H_ */
#include <asn_internal.h>
