/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_RelativeAMFCapacity_H_
#define	_RelativeAMFCapacity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RelativeAMFCapacity */
typedef long	 RelativeAMFCapacity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RelativeAMFCapacity;
asn_struct_free_f RelativeAMFCapacity_free;
asn_struct_print_f RelativeAMFCapacity_print;
asn_constr_check_f RelativeAMFCapacity_constraint;
ber_type_decoder_f RelativeAMFCapacity_decode_ber;
der_type_encoder_f RelativeAMFCapacity_encode_der;
xer_type_decoder_f RelativeAMFCapacity_decode_xer;
xer_type_encoder_f RelativeAMFCapacity_encode_xer;
oer_type_decoder_f RelativeAMFCapacity_decode_oer;
oer_type_encoder_f RelativeAMFCapacity_encode_oer;
per_type_decoder_f RelativeAMFCapacity_decode_uper;
per_type_encoder_f RelativeAMFCapacity_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RelativeAMFCapacity_H_ */
#include <asn_internal.h>
