/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_TNLAddressWeightFactor_H_
#define	_TNLAddressWeightFactor_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TNLAddressWeightFactor */
typedef long	 TNLAddressWeightFactor_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TNLAddressWeightFactor_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TNLAddressWeightFactor;
asn_struct_free_f TNLAddressWeightFactor_free;
asn_struct_print_f TNLAddressWeightFactor_print;
asn_constr_check_f TNLAddressWeightFactor_constraint;
ber_type_decoder_f TNLAddressWeightFactor_decode_ber;
der_type_encoder_f TNLAddressWeightFactor_encode_der;
xer_type_decoder_f TNLAddressWeightFactor_decode_xer;
xer_type_encoder_f TNLAddressWeightFactor_encode_xer;
oer_type_decoder_f TNLAddressWeightFactor_decode_oer;
oer_type_encoder_f TNLAddressWeightFactor_encode_oer;
per_type_decoder_f TNLAddressWeightFactor_decode_uper;
per_type_encoder_f TNLAddressWeightFactor_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TNLAddressWeightFactor_H_ */
#include <asn_internal.h>
