/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_UERadioCapabilityForPagingOfNR_H_
#define	_UERadioCapabilityForPagingOfNR_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UERadioCapabilityForPagingOfNR */
typedef OCTET_STRING_t	 UERadioCapabilityForPagingOfNR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UERadioCapabilityForPagingOfNR;
asn_struct_free_f UERadioCapabilityForPagingOfNR_free;
asn_struct_print_f UERadioCapabilityForPagingOfNR_print;
asn_constr_check_f UERadioCapabilityForPagingOfNR_constraint;
ber_type_decoder_f UERadioCapabilityForPagingOfNR_decode_ber;
der_type_encoder_f UERadioCapabilityForPagingOfNR_encode_der;
xer_type_decoder_f UERadioCapabilityForPagingOfNR_decode_xer;
xer_type_encoder_f UERadioCapabilityForPagingOfNR_encode_xer;
oer_type_decoder_f UERadioCapabilityForPagingOfNR_decode_oer;
oer_type_encoder_f UERadioCapabilityForPagingOfNR_encode_oer;
per_type_decoder_f UERadioCapabilityForPagingOfNR_decode_uper;
per_type_encoder_f UERadioCapabilityForPagingOfNR_encode_uper;
per_type_decoder_f UERadioCapabilityForPagingOfNR_decode_aper;
per_type_encoder_f UERadioCapabilityForPagingOfNR_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UERadioCapabilityForPagingOfNR_H_ */
#include <asn_internal.h>
