/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_UserLocationInformation_H_
#define	_UserLocationInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UserLocationInformation_PR {
	UserLocationInformation_PR_NOTHING,	/* No components present */
	UserLocationInformation_PR_userLocationInformationEUTRA,
	UserLocationInformation_PR_userLocationInformationNR,
	UserLocationInformation_PR_userLocationInformationN3IWF,
	UserLocationInformation_PR_choice_Extensions
} UserLocationInformation_PR;

/* Forward declarations */
struct UserLocationInformationEUTRA;
struct UserLocationInformationNR;
struct UserLocationInformationN3IWF;
struct ProtocolIE_SingleContainer;

/* UserLocationInformation */
typedef struct UserLocationInformation {
	UserLocationInformation_PR present;
	union UserLocationInformation_u {
		struct UserLocationInformationEUTRA	*userLocationInformationEUTRA;
		struct UserLocationInformationNR	*userLocationInformationNR;
		struct UserLocationInformationN3IWF	*userLocationInformationN3IWF;
		struct ProtocolIE_SingleContainer	*choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UserLocationInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UserLocationInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _UserLocationInformation_H_ */
#include <asn_internal.h>
