/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_UserLocationInformationNR_H_
#define	_UserLocationInformationNR_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NR-CGI.h"
#include "TAI.h"
#include "TimeStamp.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* UserLocationInformationNR */
typedef struct UserLocationInformationNR {
	NR_CGI_t	 nR_CGI;
	TAI_t	 tAI;
	TimeStamp_t	*timeStamp;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UserLocationInformationNR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UserLocationInformationNR;
extern asn_SEQUENCE_specifics_t asn_SPC_UserLocationInformationNR_specs_1;
extern asn_TYPE_member_t asn_MBR_UserLocationInformationNR_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _UserLocationInformationNR_H_ */
#include <asn_internal.h>
