/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "../NGAP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_XnTNLConfigurationInfo_H_
#define	_XnTNLConfigurationInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "XnTLAs.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct XnExtTLAs;
struct ProtocolExtensionContainer;

/* XnTNLConfigurationInfo */
typedef struct XnTNLConfigurationInfo {
	XnTLAs_t	 xnTransportLayerAddresses;
	struct XnExtTLAs	*xnExtendedTransportLayerAddresses	/* OPTIONAL */;
	struct ProtocolExtensionContainer	*iE_Extensions	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} XnTNLConfigurationInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_XnTNLConfigurationInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_XnTNLConfigurationInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_XnTNLConfigurationInfo_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _XnTNLConfigurationInfo_H_ */
#include <asn_internal.h>
